/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8_renatolizardo;

import java.io.BufferedWriter;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus Pc
 */
public class Principal_Hackeo extends javax.swing.JFrame {

    /**
     * Creates new form Principal_Hackeo
     */
    Random r = new Random();
    public Principal_Hackeo() {
        initComponents();
        
     
        //pgb_TiempoHackeo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HackeoSuper = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf_Codigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbb_NivelResgo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        HackeoRegular = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        cbb_NivelResgo1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tf_Codigo1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        Simulacion = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_Hackeos = new javax.swing.JList<>();
        pgb_hackeo = new javax.swing.JProgressBar();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tf_caracteres = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jd_Modificar = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_codigoModificar = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        cbb_modificar = new javax.swing.JComboBox<>();
        jd_Eliminar = new javax.swing.JDialog();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel5.setText("Codigo");

        jLabel4.setText("Nivel");

        cbb_NivelResgo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout HackeoSuperLayout = new javax.swing.GroupLayout(HackeoSuper.getContentPane());
        HackeoSuper.getContentPane().setLayout(HackeoSuperLayout);
        HackeoSuperLayout.setHorizontalGroup(
            HackeoSuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HackeoSuperLayout.createSequentialGroup()
                .addGroup(HackeoSuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HackeoSuperLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1)
                        .addGap(73, 73, 73)
                        .addGroup(HackeoSuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HackeoSuperLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(74, 74, 74)
                                .addComponent(cbb_NivelResgo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(HackeoSuperLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(67, 67, 67)
                                .addComponent(tf_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(HackeoSuperLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        HackeoSuperLayout.setVerticalGroup(
            HackeoSuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HackeoSuperLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HackeoSuperLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(HackeoSuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(HackeoSuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbb_NivelResgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );

        cbb_NivelResgo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        jLabel6.setText("Nivel");

        jLabel7.setText("Codigo");

        jButton5.setText("Agregar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HackeoRegularLayout = new javax.swing.GroupLayout(HackeoRegular.getContentPane());
        HackeoRegular.getContentPane().setLayout(HackeoRegularLayout);
        HackeoRegularLayout.setHorizontalGroup(
            HackeoRegularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HackeoRegularLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel2)
                .addGap(59, 59, 59)
                .addGroup(HackeoRegularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HackeoRegularLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(74, 74, 74)
                        .addComponent(cbb_NivelResgo1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HackeoRegularLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(67, 67, 67)
                        .addComponent(tf_Codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HackeoRegularLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        HackeoRegularLayout.setVerticalGroup(
            HackeoRegularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HackeoRegularLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(HackeoRegularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HackeoRegularLayout.createSequentialGroup()
                        .addGroup(HackeoRegularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_Codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(HackeoRegularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbb_NivelResgo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jl_Hackeos.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_Hackeos);

        pgb_hackeo.setStringPainted(true);

        jButton6.setText("Hackear");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jLabel3.setText("Caracteres a hackear");

        jButton7.setText("Modificar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("Eliminar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton10.setText("Cargar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jButton11.setText("Guardar");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SimulacionLayout = new javax.swing.GroupLayout(Simulacion.getContentPane());
        Simulacion.getContentPane().setLayout(SimulacionLayout);
        SimulacionLayout.setHorizontalGroup(
            SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimulacionLayout.createSequentialGroup()
                .addGroup(SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SimulacionLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel3)
                        .addGap(74, 74, 74)
                        .addComponent(tf_caracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SimulacionLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SimulacionLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(pgb_hackeo, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SimulacionLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SimulacionLayout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addGroup(SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton7)
                                        .addComponent(jButton8)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SimulacionLayout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(SimulacionLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jButton11)))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        SimulacionLayout.setVerticalGroup(
            SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimulacionLayout.createSequentialGroup()
                .addGroup(SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SimulacionLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SimulacionLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton7)
                        .addGap(45, 45, 45)
                        .addComponent(jButton8)
                        .addGap(45, 45, 45)
                        .addComponent(jButton10)
                        .addGap(44, 44, 44)
                        .addComponent(jButton11)))
                .addGap(133, 133, 133)
                .addGroup(SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_caracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pgb_hackeo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jLabel8.setText("Codigo");

        jLabel9.setText("Nivel");

        jButton9.setText("Modificar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        cbb_modificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout jd_ModificarLayout = new javax.swing.GroupLayout(jd_Modificar.getContentPane());
        jd_Modificar.getContentPane().setLayout(jd_ModificarLayout);
        jd_ModificarLayout.setHorizontalGroup(
            jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModificarLayout.createSequentialGroup()
                .addGroup(jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ModificarLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_codigoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_ModificarLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jd_ModificarLayout.setVerticalGroup(
            jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModificarLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_codigoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(cbb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_EliminarLayout = new javax.swing.GroupLayout(jd_Eliminar.getContentPane());
        jd_Eliminar.getContentPane().setLayout(jd_EliminarLayout);
        jd_EliminarLayout.setHorizontalGroup(
            jd_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_EliminarLayout.setVerticalGroup(
            jd_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Agregar Hackeo Super");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Agregar Hackeo Regular");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Simulacion");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jButton2)
                        .addGap(112, 112, 112)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
 DefaultListModel modelo = (DefaultListModel) jl_Hackeos.getModel();
 String nombre;
 int valor;
    nombre = tf_Codigo.getText();
        valor =  Integer.parseInt(cbb_NivelResgo.getSelectedItem().toString());
 
         hackeo = new Hackeo_Super(nombre, valor );
       
        modelo.addElement(hackeo);
        n.add(hackeo);
        
        tf_Codigo.setText("");
       cbb_NivelResgo.setSelectedItem(0);
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        DefaultListModel modelo = (DefaultListModel) jl_Hackeos.getModel();
        String nombre;
        int valor;
        nombre = tf_Codigo1.getText();
        valor = Integer.parseInt(cbb_NivelResgo1.getSelectedItem().toString());

        hackeo = new Hackeo_regular(nombre, valor);

        //regular = new AdminHackeo_Regular(pgb_TiempoHackeo, hackeo);
        modelo.addElement(hackeo);
        n.add(hackeo);
        
        tf_Codigo1.setText("");
       cbb_NivelResgo1.setSelectedItem(0);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
         HackeoSuper.setModal(true);
        HackeoSuper.pack();
        HackeoSuper.setLocationRelativeTo(this);
        HackeoSuper.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
         HackeoRegular.setModal(true);
        HackeoRegular.pack();
        HackeoRegular.setLocationRelativeTo(this);
        HackeoRegular.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
         Simulacion.setModal(true);
        Simulacion.pack();
        Simulacion.setLocationRelativeTo(this);
        Simulacion.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        DefaultListModel modelo = (DefaultListModel) jl_Hackeos.getModel();
        int aleatorio;
        int caracteres;
        
        Hackeo m = (Hackeo)modelo.getElementAt(jl_Hackeos.getSelectedIndex());
        System.out.println(m);
        aleatorio = 1+r.nextInt(10);
        
        caracteres = tf_caracteres.getText().length();
        
        
        if (m.getClass().toString().contains("Hackeo_Super")) {
            if (m.getNivel() == aleatorio) {
                ((Hackeo_Super) m).setFallidos(((Hackeo_Super) m).getFallidos()+1);
                System.out.println("chingaste");
            }else{
                System.out.println("sadasd");
                regular = new AdminHackeo_Regular(this.pgb_hackeo, m , caracteres);
               
                regular.start();
            }
        }
        
          if (m.getClass().toString().contains("Hackeo_regular")) {
            if (m.getNivel() == aleatorio) {
                ((Hackeo_regular) m).setExitoso(((Hackeo_regular) m).getExitoso()+1);
                System.out.println("chingaste");
            }else{
                System.out.println("sadasd");
                regular = new AdminHackeo_Regular(this.pgb_hackeo, m , caracteres);
                regular.start();
               
                
            }
        }
        
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
      
           DefaultListModel modeloLISTA2 = (DefaultListModel) jl_Hackeos.getModel();

        Hackeo m = (Hackeo) modeloLISTA2.getElementAt(jl_Hackeos.getSelectedIndex());
       
       tf_codigoModificar.setText(m.getCodigo());
       cbb_modificar.setSelectedItem(m.getNivel());
        
        jd_Modificar.setModal(true);
        jd_Modificar.pack();
        jd_Modificar.setLocationRelativeTo(this);
        jd_Modificar.setVisible(true);
       
          
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        String Codigo;
        int nivel;

        DefaultListModel modeloLISTA2 = (DefaultListModel) jl_Hackeos.getModel();

        Hackeo m = (Hackeo) modeloLISTA2.getElementAt(jl_Hackeos.getSelectedIndex());
  
       
       
       Codigo = tf_codigoModificar.getText();
       nivel = Integer.parseInt(cbb_modificar.getSelectedItem().toString());
       
       
       m.setCodigo(Codigo);
       m.setNivel(nivel);
       
       tf_codigoModificar.setText("");
       cbb_modificar.setSelectedItem(0);
        
 
        
       
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        DefaultListModel modeloLISTA2 = (DefaultListModel) jl_Hackeos.getModel();

        Hackeo m = (Hackeo) modeloLISTA2.getElementAt(jl_Hackeos.getSelectedIndex());

        modeloLISTA2.remove(jl_Hackeos.getSelectedIndex());
    }//GEN-LAST:event_jButton8MouseClicked

    
    
        public void cargarArchivo(){
             //DefaultListModel modeloLISTA2 = (DefaultListModel) jl_Hackeos.getModel();

      
            
           Scanner sc = null;
        Scanner sc2 = null;
        n = new ArrayList();
        
    
           Hackeo p; 
        
        try {
            sc = new Scanner("./Rena.txt");
            sc.useDelimiter(";");
            sc2 = sc;
            sc2.useDelimiter(",");
            
            while(sc.hasNext()){
                
                if (sc.next().contains("Hackeo_Super")) {
                     p = new Hackeo_Super(sc.next(),sc.nextInt());
                     n.add(p);
                }else{
                    p = new Hackeo_regular(sc.next(),sc.nextInt());
                }
      
                //listaPersonas.add(new Personas(sc.nextInt(),sc.next(),sc.nextInt()));
                
                
                
            }
            
        }catch(Exception ex){
            
        }
        sc2.close();
        sc.close();
        
        
    
      
    }
    
    
       public void escribirArchivo() throws IOException{
           
           
         FileWriter fw = null;
        BufferedWriter bw = null;
        try{
        fw = new FileWriter("./Rena.txt",true);
        bw = new BufferedWriter(fw);
        for (Hackeo t : n) {
           bw.write(t.getClass().toString()+";");
            bw.write(t.getCodigo()+";");
            bw.write(t.getNivel()+";");
   
        }
        
        bw.flush();
        }
        catch(Exception e){
            //System.out.println("hasbdkasdbjas");
        }
        bw.close();
        fw.close();
        
        
    }
       
    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        try {
       
            //int p = jl_Hackeos.getSelectedIndex();
            DefaultListModel modelo = (DefaultListModel) jl_Hackeos.getModel();
            
            archivoHackeo ahack = new archivoHackeo("./Rena.rld");
            ahack.cargarArchivo();
            
            try {
            for (int i = 0; i < modelo.getSize(); i++) {
            ahack.getLista().add(((Hackeo)modelo.get(i)));
            }
            ahack.escribirArchivo();
            JOptionPane.showMessageDialog(this, "Archivo Creado");
            } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            }
        }catch(Exception e){
            
        }
            
        
        
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
  try{
            ArrayList temp = new ArrayList();
            Hackeo t;
            DefaultListModel modelo = (DefaultListModel) jl_Hackeos.getModel();
            
            FileInputStream entrada = new FileInputStream("./Rena.rld");
            ObjectInputStream objeto = new ObjectInputStream(entrada);
            try {
                while ((t=(Hackeo)objeto.readObject())!=null) {
                    temp.add(t);
                    modelo.addElement(t);
                }
                objeto.close();
                entrada.close();
            } catch (Exception e) {
            }
        } catch (Exception e) {
        }
     
      /* 
       cargarArchivo();
         DefaultListModel modelo = (DefaultListModel) jl_Hackeos.getModel();
         System.out.println(n);
        for (int i = 0; i < n.size(); i++) {
            modelo.addElement(n.get(i));
            jl_Hackeos.setModel(modelo);
        }*/
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_Hackeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_Hackeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_Hackeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_Hackeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_Hackeo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog HackeoRegular;
    private javax.swing.JDialog HackeoSuper;
    private javax.swing.JDialog Simulacion;
    private javax.swing.JComboBox<String> cbb_NivelResgo;
    private javax.swing.JComboBox<String> cbb_NivelResgo1;
    private javax.swing.JComboBox<String> cbb_modificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jd_Eliminar;
    private javax.swing.JDialog jd_Modificar;
    private javax.swing.JList<String> jl_Hackeos;
    private javax.swing.JProgressBar pgb_hackeo;
    private javax.swing.JTextField tf_Codigo;
    private javax.swing.JTextField tf_Codigo1;
    private javax.swing.JTextField tf_caracteres;
    private javax.swing.JTextField tf_codigoModificar;
    // End of variables declaration//GEN-END:variables
    Hackeo hackeo ;
    AdminHackeo_Regular regular;
    ArrayList<Hackeo> n = new ArrayList();
}
